import turtle
drawing_board = turtle.Screen()
drawing_board.bgcolor("green")
drawing_board.title("Python Turtle")
turtle_instance = turtle.Turtle()
turtle_instance.forward(222)
turtle_instance.left(90)
turtle_instance.forward(222)
turtle_instance.left(90)
turtle_instance.forward(222)
turtle_instance.left(90)
turtle_instance.forward(222)
turtle.done()
